version: '3.8'

services:
  postgres_db:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - pipeline-airflow-1_2ffd5d_airflow
    ports:
      - "5433:5432"
  
  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    networks:
      - pipeline-airflow-1_2ffd5d_airflow
    ports:
      - "8978:8978"
    environment:
      - DISPLAY=:0

networks:
  pipeline-airflow-1_2ffd5d_airflow:
    external: true


